.nh
.TH "AI-DETECTION" "1" "Mar 2026" "" ""

.SH NAME
ai-detection - Detect AI-generated contributions


.SH SYNOPSIS
\fBai-detection [flags]\fP


.SH DESCRIPTION
Detect AI-generated contributions


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for ai-detection


.SH SEE ALSO
\fBai-detection-completion(1)\fP, \fBai-detection-docs(1)\fP, \fBai-detection-scan(1)\fP, \fBai-detection-text(1)\fP, \fBai-detection-version(1)\fP
